Attribute VB_Name = "工作表38"
Attribute VB_Base = "0{00020820-0000-0000-C000-000000000046}"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = True
Attribute VB_Exposed = True
Attribute VB_TemplateDerived = False
Attribute VB_Customizable = True
Attribute VB_Control = "CheckBox1, 28, 0, MSForms, CheckBox"
Private Sub CheckBox1_Click()

    Dim i6_1Cht As ChartObject
    Dim i6_2Cht As ChartObject
    Dim i6_3Cht As ChartObject
    Dim i6_4Cht As ChartObject
    Dim i6_5Cht As ChartObject
    Dim i6_6Cht As ChartObject
    If Range("Q1") = "1" Then
        Set i6_1Cht = Me.ChartObjects("近6月營收年增率22")
        i6_1Cht.Visible = 0
        Set i6_2Cht = Me.ChartObjects("近6季營業利益率22")
        i6_2Cht.Visible = 0
        Set i6_3Cht = Me.ChartObjects("近6季稅後淨利年增率22")
        i6_3Cht.Visible = 0
        Set i6_4Cht = Me.ChartObjects("近6季每股盈餘EPS22")
        i6_4Cht.Visible = 0
        Set i6_5Cht = Me.ChartObjects("近6季存貨周轉率22")
        i6_5Cht.Visible = 0
        Set i6_6Cht = Me.ChartObjects("近6季自由現金流量22")
        i6_6Cht.Visible = 0
        Set i6_1Cht = Me.ChartObjects("近6月營收年增率23")
        i6_1Cht.Visible = 0
        Set i6_2Cht = Me.ChartObjects("近6季營業利益率23")
        i6_2Cht.Visible = 0
        Set i6_3Cht = Me.ChartObjects("近6季稅後淨利年增率23")
        i6_3Cht.Visible = 0
        Set i6_4Cht = Me.ChartObjects("近6季每股盈餘EPS23")
        i6_4Cht.Visible = 0
        Set i6_5Cht = Me.ChartObjects("近6季存貨周轉率23")
        i6_5Cht.Visible = 0
        Set i6_6Cht = Me.ChartObjects("近6季自由現金流量23")
        i6_6Cht.Visible = 0
        Set i6_1Cht = Me.ChartObjects("近6月營收年增率24")
        i6_1Cht.Visible = 0
        Set i6_2Cht = Me.ChartObjects("近6季營業利益率24")
        i6_2Cht.Visible = 0
        Set i6_3Cht = Me.ChartObjects("近6季稅後淨利年增率24")
        i6_3Cht.Visible = 0
        Set i6_4Cht = Me.ChartObjects("近6季每股盈餘EPS24")
        i6_4Cht.Visible = 0
        Set i6_5Cht = Me.ChartObjects("近6季存貨周轉率24")
        i6_5Cht.Visible = 0
        Set i6_6Cht = Me.ChartObjects("近6季自由現金流量24")
        i6_6Cht.Visible = 0
        
        Set i6_1Cht = Me.ChartObjects("近6月營收年增率2")
        i6_1Cht.Visible = CheckBox1.Value
        Set i6_2Cht = Me.ChartObjects("近6季營業利益率2")
        i6_2Cht.Visible = CheckBox1.Value
        Set i6_3Cht = Me.ChartObjects("近6季稅後淨利年增率2")
        i6_3Cht.Visible = CheckBox1.Value
        Set i6_4Cht = Me.ChartObjects("近6季每股盈餘EPS2")
        i6_4Cht.Visible = CheckBox1.Value
        Set i6_5Cht = Me.ChartObjects("近6季存貨周轉率2")
        i6_5Cht.Visible = CheckBox1.Value
        Set i6_6Cht = Me.ChartObjects("近6季自由現金流量2")
        i6_6Cht.Visible = CheckBox1.Value
    ElseIf Range("Q1") = 2 Then
        Set i6_1Cht = Me.ChartObjects("近6月營收年增率2")
        i6_1Cht.Visible = 0
        Set i6_2Cht = Me.ChartObjects("近6季營業利益率2")
        i6_2Cht.Visible = 0
        Set i6_3Cht = Me.ChartObjects("近6季稅後淨利年增率2")
        i6_3Cht.Visible = 0
        Set i6_4Cht = Me.ChartObjects("近6季每股盈餘EPS2")
        i6_4Cht.Visible = 0
        Set i6_5Cht = Me.ChartObjects("近6季存貨周轉率2")
        i6_5Cht.Visible = 0
        Set i6_6Cht = Me.ChartObjects("近6季自由現金流量2")
        i6_6Cht.Visible = 0
        Set i6_1Cht = Me.ChartObjects("近6月營收年增率23")
        i6_1Cht.Visible = 0
        Set i6_2Cht = Me.ChartObjects("近6季營業利益率23")
        i6_2Cht.Visible = 0
        Set i6_3Cht = Me.ChartObjects("近6季稅後淨利年增率23")
        i6_3Cht.Visible = 0
        Set i6_4Cht = Me.ChartObjects("近6季每股盈餘EPS23")
        i6_4Cht.Visible = 0
        Set i6_5Cht = Me.ChartObjects("近6季存貨周轉率23")
        i6_5Cht.Visible = 0
        Set i6_6Cht = Me.ChartObjects("近6季自由現金流量23")
        i6_6Cht.Visible = 0
        Set i6_1Cht = Me.ChartObjects("近6月營收年增率24")
        i6_1Cht.Visible = 0
        Set i6_2Cht = Me.ChartObjects("近6季營業利益率24")
        i6_2Cht.Visible = 0
        Set i6_3Cht = Me.ChartObjects("近6季稅後淨利年增率24")
        i6_3Cht.Visible = 0
        Set i6_4Cht = Me.ChartObjects("近6季每股盈餘EPS24")
        i6_4Cht.Visible = 0
        Set i6_5Cht = Me.ChartObjects("近6季存貨周轉率24")
        i6_5Cht.Visible = 0
        Set i6_6Cht = Me.ChartObjects("近6季自由現金流量24")
        i6_6Cht.Visible = 0
        
        Set i6_1Cht = Me.ChartObjects("近6月營收年增率22")
        i6_1Cht.Visible = CheckBox1.Value
        Set i6_2Cht = Me.ChartObjects("近6季營業利益率22")
        i6_2Cht.Visible = CheckBox1.Value
        Set i6_3Cht = Me.ChartObjects("近6季稅後淨利年增率22")
        i6_3Cht.Visible = CheckBox1.Value
        Set i6_4Cht = Me.ChartObjects("近6季每股盈餘EPS22")
        i6_4Cht.Visible = CheckBox1.Value
        Set i6_5Cht = Me.ChartObjects("近6季存貨周轉率22")
        i6_5Cht.Visible = CheckBox1.Value
        Set i6_6Cht = Me.ChartObjects("近6季自由現金流量22")
        i6_6Cht.Visible = CheckBox1.Value
    ElseIf Range("Q1") = 3 Then
        Set i6_1Cht = Me.ChartObjects("近6月營收年增率2")
        i6_1Cht.Visible = 0
        Set i6_2Cht = Me.ChartObjects("近6季營業利益率2")
        i6_2Cht.Visible = 0
        Set i6_3Cht = Me.ChartObjects("近6季稅後淨利年增率2")
        i6_3Cht.Visible = 0
        Set i6_4Cht = Me.ChartObjects("近6季每股盈餘EPS2")
        i6_4Cht.Visible = 0
        Set i6_5Cht = Me.ChartObjects("近6季存貨周轉率2")
        i6_5Cht.Visible = 0
        Set i6_6Cht = Me.ChartObjects("近6季自由現金流量2")
        i6_6Cht.Visible = 0
         Set i6_1Cht = Me.ChartObjects("近6月營收年增率22")
        i6_1Cht.Visible = 0
        Set i6_2Cht = Me.ChartObjects("近6季營業利益率22")
        i6_2Cht.Visible = 0
        Set i6_3Cht = Me.ChartObjects("近6季稅後淨利年增率22")
        i6_3Cht.Visible = 0
        Set i6_4Cht = Me.ChartObjects("近6季每股盈餘EPS22")
        i6_4Cht.Visible = 0
        Set i6_5Cht = Me.ChartObjects("近6季存貨周轉率22")
        i6_5Cht.Visible = 0
        Set i6_6Cht = Me.ChartObjects("近6季自由現金流量22")
        i6_6Cht.Visible = 0
        Set i6_1Cht = Me.ChartObjects("近6月營收年增率24")
        i6_1Cht.Visible = 0
        Set i6_2Cht = Me.ChartObjects("近6季營業利益率24")
        i6_2Cht.Visible = 0
        Set i6_3Cht = Me.ChartObjects("近6季稅後淨利年增率24")
        i6_3Cht.Visible = 0
        Set i6_4Cht = Me.ChartObjects("近6季每股盈餘EPS24")
        i6_4Cht.Visible = 0
        Set i6_5Cht = Me.ChartObjects("近6季存貨周轉率24")
        i6_5Cht.Visible = 0
        Set i6_6Cht = Me.ChartObjects("近6季自由現金流量24")
        i6_6Cht.Visible = 0
       
        Set i6_1Cht = Me.ChartObjects("近6月營收年增率23")
        i6_1Cht.Visible = CheckBox1.Value
        Set i6_2Cht = Me.ChartObjects("近6季營業利益率23")
        i6_2Cht.Visible = CheckBox1.Value
        Set i6_3Cht = Me.ChartObjects("近6季稅後淨利年增率23")
        i6_3Cht.Visible = CheckBox1.Value
        Set i6_4Cht = Me.ChartObjects("近6季每股盈餘EPS23")
        i6_4Cht.Visible = CheckBox1.Value
        Set i6_5Cht = Me.ChartObjects("近6季存貨周轉率22")
        i6_5Cht.Visible = CheckBox1.Value
        Set i6_6Cht = Me.ChartObjects("近6季自由現金流量22")
        i6_6Cht.Visible = CheckBox1.Value
        
    ElseIf Range("Q1") = 4 Then
        Set i6_1Cht = Me.ChartObjects("近6月營收年增率2")
        i6_1Cht.Visible = 0
        Set i6_2Cht = Me.ChartObjects("近6季營業利益率2")
        i6_2Cht.Visible = 0
        Set i6_3Cht = Me.ChartObjects("近6季稅後淨利年增率2")
        i6_3Cht.Visible = 0
        Set i6_4Cht = Me.ChartObjects("近6季每股盈餘EPS2")
        i6_4Cht.Visible = 0
        Set i6_5Cht = Me.ChartObjects("近6季存貨周轉率2")
        i6_5Cht.Visible = 0
        Set i6_6Cht = Me.ChartObjects("近6季自由現金流量2")
        i6_6Cht.Visible = 0
         Set i6_1Cht = Me.ChartObjects("近6月營收年增率22")
        i6_1Cht.Visible = 0
        Set i6_2Cht = Me.ChartObjects("近6季營業利益率22")
        i6_2Cht.Visible = 0
        Set i6_3Cht = Me.ChartObjects("近6季稅後淨利年增率22")
        i6_3Cht.Visible = 0
        Set i6_4Cht = Me.ChartObjects("近6季每股盈餘EPS22")
        i6_4Cht.Visible = 0
        Set i6_5Cht = Me.ChartObjects("近6季存貨周轉率22")
        i6_5Cht.Visible = 0
        Set i6_6Cht = Me.ChartObjects("近6季自由現金流量22")
        i6_6Cht.Visible = 0
        Set i6_1Cht = Me.ChartObjects("近6月營收年增率23")
        i6_1Cht.Visible = 0
        Set i6_2Cht = Me.ChartObjects("近6季營業利益率23")
        i6_2Cht.Visible = 0
        Set i6_3Cht = Me.ChartObjects("近6季稅後淨利年增率23")
        i6_3Cht.Visible = 0
        Set i6_4Cht = Me.ChartObjects("近6季每股盈餘EPS23")
        i6_4Cht.Visible = 0
        Set i6_5Cht = Me.ChartObjects("近6季存貨周轉率23")
        i6_5Cht.Visible = 0
        Set i6_6Cht = Me.ChartObjects("近6季自由現金流量23")
        i6_6Cht.Visible = 0
       
        Set i6_1Cht = Me.ChartObjects("近6月營收年增率24")
        i6_1Cht.Visible = CheckBox1.Value
        Set i6_2Cht = Me.ChartObjects("近6季營業利益率24")
        i6_2Cht.Visible = CheckBox1.Value
        Set i6_3Cht = Me.ChartObjects("近6季稅後淨利年增率24")
        i6_3Cht.Visible = CheckBox1.Value
        Set i6_4Cht = Me.ChartObjects("近6季每股盈餘EPS24")
        i6_4Cht.Visible = CheckBox1.Value
        Set i6_5Cht = Me.ChartObjects("近6季存貨周轉率24")
        i6_5Cht.Visible = CheckBox1.Value
        Set i6_6Cht = Me.ChartObjects("近6季自由現金流量24")
        i6_6Cht.Visible = CheckBox1.Value
    End If

End Sub

Private Sub Worksheet_Change(ByVal Target As Range)

    Dim i6_1Cht As ChartObject
    Dim i6_2Cht As ChartObject
    Dim i6_3Cht As ChartObject
    Dim i6_4Cht As ChartObject
    Dim i6_5Cht As ChartObject
    Dim i6_6Cht As ChartObject
    If Target.Address = "$Q$1" Then
        Select Case Range("$Q$1")
        Case 1
            Set i6_1Cht = Me.ChartObjects("近6月營收年增率2")
            i6_1Cht.Visible = CheckBox1.Value
            Set i6_2Cht = Me.ChartObjects("近6季營業利益率2")
            i6_2Cht.Visible = CheckBox1.Value
            Set i6_3Cht = Me.ChartObjects("近6季稅後淨利年增率2")
            i6_3Cht.Visible = CheckBox1.Value
            Set i6_4Cht = Me.ChartObjects("近6季每股盈餘EPS2")
            i6_4Cht.Visible = CheckBox1.Value
            Set i6_5Cht = Me.ChartObjects("近6季存貨周轉率2")
            i6_5Cht.Visible = CheckBox1.Value
            Set i6_6Cht = Me.ChartObjects("近6季自由現金流量2")
            i6_6Cht.Visible = CheckBox1.Value
    
            Set i6_1Cht = Me.ChartObjects("近6月營收年增率22")
            i6_1Cht.Visible = 0
            Set i6_2Cht = Me.ChartObjects("近6季營業利益率22")
            i6_2Cht.Visible = 0
            Set i6_3Cht = Me.ChartObjects("近6季稅後淨利年增率22")
            i6_3Cht.Visible = 0
            Set i6_4Cht = Me.ChartObjects("近6季每股盈餘EPS22")
            i6_4Cht.Visible = 0
            Set i6_5Cht = Me.ChartObjects("近6季存貨周轉率22")
            i6_5Cht.Visible = 0
            Set i6_6Cht = Me.ChartObjects("近6季自由現金流量22")
            i6_6Cht.Visible = 0
            Set i6_1Cht = Me.ChartObjects("近6月營收年增率23")
            i6_1Cht.Visible = 0
            Set i6_2Cht = Me.ChartObjects("近6季營業利益率23")
            i6_2Cht.Visible = 0
            Set i6_3Cht = Me.ChartObjects("近6季稅後淨利年增率23")
            i6_3Cht.Visible = 0
            Set i6_4Cht = Me.ChartObjects("近6季每股盈餘EPS23")
            i6_4Cht.Visible = 0
            Set i6_5Cht = Me.ChartObjects("近6季存貨周轉率23")
            i6_5Cht.Visible = 0
            Set i6_6Cht = Me.ChartObjects("近6季自由現金流量23")
            i6_6Cht.Visible = 0
            Set i6_1Cht = Me.ChartObjects("近6月營收年增率24")
            i6_1Cht.Visible = 0
            Set i6_2Cht = Me.ChartObjects("近6季營業利益率24")
            i6_2Cht.Visible = 0
            Set i6_3Cht = Me.ChartObjects("近6季稅後淨利年增率24")
            i6_3Cht.Visible = 0
            Set i6_4Cht = Me.ChartObjects("近6季每股盈餘EPS24")
            i6_4Cht.Visible = 0
            Set i6_5Cht = Me.ChartObjects("近6季存貨周轉率24")
            i6_5Cht.Visible = 0
            Set i6_6Cht = Me.ChartObjects("近6季自由現金流量24")
            i6_6Cht.Visible = 0
        Case 2
            Set i6_1Cht = Me.ChartObjects("近6月營收年增率22")
            i6_1Cht.Visible = CheckBox1.Value
            Set i6_2Cht = Me.ChartObjects("近6季營業利益率22")
            i6_2Cht.Visible = CheckBox1.Value
            Set i6_3Cht = Me.ChartObjects("近6季稅後淨利年增率22")
            i6_3Cht.Visible = CheckBox1.Value
            Set i6_4Cht = Me.ChartObjects("近6季每股盈餘EPS22")
            i6_4Cht.Visible = CheckBox1.Value
            Set i6_5Cht = Me.ChartObjects("近6季存貨周轉率22")
            i6_5Cht.Visible = CheckBox1.Value
            Set i6_6Cht = Me.ChartObjects("近6季自由現金流量22")
            i6_6Cht.Visible = CheckBox1.Value
    
            Set i6_1Cht = Me.ChartObjects("近6月營收年增率2")
            i6_1Cht.Visible = 0
            Set i6_2Cht = Me.ChartObjects("近6季營業利益率2")
            i6_2Cht.Visible = 0
            Set i6_3Cht = Me.ChartObjects("近6季稅後淨利年增率2")
            i6_3Cht.Visible = 0
            Set i6_4Cht = Me.ChartObjects("近6季每股盈餘EPS2")
            i6_4Cht.Visible = 0
            Set i6_5Cht = Me.ChartObjects("近6季存貨周轉率2")
            i6_5Cht.Visible = 0
            Set i6_6Cht = Me.ChartObjects("近6季自由現金流量2")
            i6_6Cht.Visible = 0
            Set i6_1Cht = Me.ChartObjects("近6月營收年增率23")
            i6_1Cht.Visible = 0
            Set i6_2Cht = Me.ChartObjects("近6季營業利益率23")
            i6_2Cht.Visible = 0
            Set i6_3Cht = Me.ChartObjects("近6季稅後淨利年增率23")
            i6_3Cht.Visible = 0
            Set i6_4Cht = Me.ChartObjects("近6季每股盈餘EPS23")
            i6_4Cht.Visible = 0
            Set i6_5Cht = Me.ChartObjects("近6季存貨周轉率23")
            i6_5Cht.Visible = 0
            Set i6_6Cht = Me.ChartObjects("近6季自由現金流量23")
            i6_6Cht.Visible = 0
            Set i6_1Cht = Me.ChartObjects("近6月營收年增率24")
            i6_1Cht.Visible = 0
            Set i6_2Cht = Me.ChartObjects("近6季營業利益率24")
            i6_2Cht.Visible = 0
            Set i6_3Cht = Me.ChartObjects("近6季稅後淨利年增率24")
            i6_3Cht.Visible = 0
            Set i6_4Cht = Me.ChartObjects("近6季每股盈餘EPS24")
            i6_4Cht.Visible = 0
            Set i6_5Cht = Me.ChartObjects("近6季存貨周轉率24")
            i6_5Cht.Visible = 0
            Set i6_6Cht = Me.ChartObjects("近6季自由現金流量24")
            i6_6Cht.Visible = 0
        Case 3
            Set i6_1Cht = Me.ChartObjects("近6月營收年增率23")
            i6_1Cht.Visible = CheckBox1.Value
            Set i6_2Cht = Me.ChartObjects("近6季營業利益率23")
            i6_2Cht.Visible = CheckBox1.Value
            Set i6_3Cht = Me.ChartObjects("近6季稅後淨利年增率23")
            i6_3Cht.Visible = CheckBox1.Value
            Set i6_4Cht = Me.ChartObjects("近6季每股盈餘EPS23")
            i6_4Cht.Visible = CheckBox1.Value
            Set i6_5Cht = Me.ChartObjects("近6季存貨周轉率23")
            i6_5Cht.Visible = CheckBox1.Value
            Set i6_6Cht = Me.ChartObjects("近6季自由現金流量23")
            i6_6Cht.Visible = CheckBox1.Value
    
            Set i6_1Cht = Me.ChartObjects("近6月營收年增率2")
            i6_1Cht.Visible = 0
            Set i6_2Cht = Me.ChartObjects("近6季營業利益率2")
            i6_2Cht.Visible = 0
            Set i6_3Cht = Me.ChartObjects("近6季稅後淨利年增率2")
            i6_3Cht.Visible = 0
            Set i6_4Cht = Me.ChartObjects("近6季每股盈餘EPS2")
            i6_4Cht.Visible = 0
            Set i6_5Cht = Me.ChartObjects("近6季存貨周轉率2")
            i6_5Cht.Visible = 0
            Set i6_6Cht = Me.ChartObjects("近6季自由現金流量2")
            i6_6Cht.Visible = 0
            Set i6_1Cht = Me.ChartObjects("近6月營收年增率22")
            i6_1Cht.Visible = 0
            Set i6_2Cht = Me.ChartObjects("近6季營業利益率22")
            i6_2Cht.Visible = 0
            Set i6_3Cht = Me.ChartObjects("近6季稅後淨利年增率22")
            i6_3Cht.Visible = 0
            Set i6_4Cht = Me.ChartObjects("近6季每股盈餘EPS22")
            i6_4Cht.Visible = 0
            Set i6_5Cht = Me.ChartObjects("近6季存貨周轉率22")
            i6_5Cht.Visible = 0
            Set i6_6Cht = Me.ChartObjects("近6季自由現金流量22")
            i6_6Cht.Visible = 0
            Set i6_1Cht = Me.ChartObjects("近6月營收年增率24")
            i6_1Cht.Visible = 0
            Set i6_2Cht = Me.ChartObjects("近6季營業利益率24")
            i6_2Cht.Visible = 0
            Set i6_3Cht = Me.ChartObjects("近6季稅後淨利年增率24")
            i6_3Cht.Visible = 0
            Set i6_4Cht = Me.ChartObjects("近6季每股盈餘EPS24")
            i6_4Cht.Visible = 0
            Set i6_5Cht = Me.ChartObjects("近6季存貨周轉率24")
            i6_5Cht.Visible = 0
            Set i6_6Cht = Me.ChartObjects("近6季自由現金流量24")
            i6_6Cht.Visible = 0
        Case 4
            Set i6_1Cht = Me.ChartObjects("近6月營收年增率24")
            i6_1Cht.Visible = CheckBox1.Value
            Set i6_2Cht = Me.ChartObjects("近6季營業利益率24")
            i6_2Cht.Visible = CheckBox1.Value
            Set i6_3Cht = Me.ChartObjects("近6季稅後淨利年增率24")
            i6_3Cht.Visible = CheckBox1.Value
            Set i6_4Cht = Me.ChartObjects("近6季每股盈餘EPS24")
            i6_4Cht.Visible = CheckBox1.Value
            Set i6_5Cht = Me.ChartObjects("近6季存貨周轉率24")
            i6_5Cht.Visible = CheckBox1.Value
            Set i6_6Cht = Me.ChartObjects("近6季自由現金流量24")
            i6_6Cht.Visible = CheckBox1.Value
    
            Set i6_1Cht = Me.ChartObjects("近6月營收年增率2")
            i6_1Cht.Visible = 0
            Set i6_2Cht = Me.ChartObjects("近6季營業利益率2")
            i6_2Cht.Visible = 0
            Set i6_3Cht = Me.ChartObjects("近6季稅後淨利年增率2")
            i6_3Cht.Visible = 0
            Set i6_4Cht = Me.ChartObjects("近6季每股盈餘EPS2")
            i6_4Cht.Visible = 0
            Set i6_5Cht = Me.ChartObjects("近6季存貨周轉率2")
            i6_5Cht.Visible = 0
            Set i6_6Cht = Me.ChartObjects("近6季自由現金流量2")
            i6_6Cht.Visible = 0
            Set i6_1Cht = Me.ChartObjects("近6月營收年增率22")
            i6_1Cht.Visible = 0
            Set i6_2Cht = Me.ChartObjects("近6季營業利益率22")
            i6_2Cht.Visible = 0
            Set i6_3Cht = Me.ChartObjects("近6季稅後淨利年增率22")
            i6_3Cht.Visible = 0
            Set i6_4Cht = Me.ChartObjects("近6季每股盈餘EPS22")
            i6_4Cht.Visible = 0
            Set i6_5Cht = Me.ChartObjects("近6季存貨周轉率22")
            i6_5Cht.Visible = 0
            Set i6_6Cht = Me.ChartObjects("近6季自由現金流量22")
            i6_6Cht.Visible = 0
            Set i6_1Cht = Me.ChartObjects("近6月營收年增率23")
            i6_1Cht.Visible = 0
            Set i6_2Cht = Me.ChartObjects("近6季營業利益率23")
            i6_2Cht.Visible = 0
            Set i6_3Cht = Me.ChartObjects("近6季稅後淨利年增率23")
            i6_3Cht.Visible = 0
            Set i6_4Cht = Me.ChartObjects("近6季每股盈餘EPS23")
            i6_4Cht.Visible = 0
            Set i6_5Cht = Me.ChartObjects("近6季存貨周轉率23")
            i6_5Cht.Visible = 0
            Set i6_6Cht = Me.ChartObjects("近6季自由現金流量23")
            i6_6Cht.Visible = 0
        End Select
    End If

End Sub
